name: Build & publish

on:
  release:
    types: [ published ]
    tags:
      - 'v*'

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            msztorc/appd-php-agent-proxy
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          flavor: |
            latest=auto
            prefix=
            suffix=
          labels: |
            maintainer=Miroslaw Sztorc
            org.opencontainers.image.title=appd-php-agent-proxy
            org.opencontainers.image.description=Appdynamics PHP Agent Sidecar Proxy


      - name: Build image appd-php-agent-proxy
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


